//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/ControlesJugadores/ControlesJuego.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlesJuego: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlesJuego()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlesJuego"",
    ""maps"": [
        {
            ""name"": ""J1"",
            ""id"": ""1191b243-b890-4185-bf24-e7febdf2a854"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""479e6513-e160-4494-8ccc-a3b0b4d8040b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GuardarCarta"",
                    ""type"": ""Button"",
                    ""id"": ""c2c8fb38-d672-4f38-a218-fcd34a5f4206"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JugarCarta"",
                    ""type"": ""Button"",
                    ""id"": ""e930b6e8-4868-441d-86f4-6ecb24e30ad3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ff527021-f211-4c02-933e-5976594c46ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74214943-c580-44e4-98eb-ad7eebe17902"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8607c725-d935-4808-84b1-8354e29bab63"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e52207f4-ea14-473d-9b87-bccbedffd96c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GuardarCarta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d68d8b7a-0273-4996-a49a-0b63ec2c37a9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JugarCarta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""J2"",
            ""id"": ""d8921ff5-2257-4452-96c5-12a8fede0e68"",
            ""actions"": [
                {
                    ""name"": ""JugarCarta"",
                    ""type"": ""Button"",
                    ""id"": ""8dad740c-3058-4f77-92f9-b662f8e7bee0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GuardarCarta"",
                    ""type"": ""Button"",
                    ""id"": ""81dbc07b-8b26-4c51-80a5-87c0277d14a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f1ad369f-67e1-4fcf-94a6-256ed63de17a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6cd081c8-db54-4bb2-8a34-2af3648173fa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3e18af90-0b17-44d2-b0e3-b50727c30d01"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9f7614eb-c73b-4842-b4ec-358f84725ab6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c2254d9f-ec47-4ea1-a282-c3287496f115"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GuardarCarta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ee9a8c-809b-4ca2-870a-0ed4ef729c21"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JugarCarta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // J1
        m_J1 = asset.FindActionMap("J1", throwIfNotFound: true);
        m_J1_Navigate = m_J1.FindAction("Navigate", throwIfNotFound: true);
        m_J1_GuardarCarta = m_J1.FindAction("GuardarCarta", throwIfNotFound: true);
        m_J1_JugarCarta = m_J1.FindAction("JugarCarta", throwIfNotFound: true);
        // J2
        m_J2 = asset.FindActionMap("J2", throwIfNotFound: true);
        m_J2_JugarCarta = m_J2.FindAction("JugarCarta", throwIfNotFound: true);
        m_J2_GuardarCarta = m_J2.FindAction("GuardarCarta", throwIfNotFound: true);
        m_J2_Navigate = m_J2.FindAction("Navigate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // J1
    private readonly InputActionMap m_J1;
    private List<IJ1Actions> m_J1ActionsCallbackInterfaces = new List<IJ1Actions>();
    private readonly InputAction m_J1_Navigate;
    private readonly InputAction m_J1_GuardarCarta;
    private readonly InputAction m_J1_JugarCarta;
    public struct J1Actions
    {
        private @ControlesJuego m_Wrapper;
        public J1Actions(@ControlesJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_J1_Navigate;
        public InputAction @GuardarCarta => m_Wrapper.m_J1_GuardarCarta;
        public InputAction @JugarCarta => m_Wrapper.m_J1_JugarCarta;
        public InputActionMap Get() { return m_Wrapper.m_J1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(J1Actions set) { return set.Get(); }
        public void AddCallbacks(IJ1Actions instance)
        {
            if (instance == null || m_Wrapper.m_J1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_J1ActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @GuardarCarta.started += instance.OnGuardarCarta;
            @GuardarCarta.performed += instance.OnGuardarCarta;
            @GuardarCarta.canceled += instance.OnGuardarCarta;
            @JugarCarta.started += instance.OnJugarCarta;
            @JugarCarta.performed += instance.OnJugarCarta;
            @JugarCarta.canceled += instance.OnJugarCarta;
        }

        private void UnregisterCallbacks(IJ1Actions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @GuardarCarta.started -= instance.OnGuardarCarta;
            @GuardarCarta.performed -= instance.OnGuardarCarta;
            @GuardarCarta.canceled -= instance.OnGuardarCarta;
            @JugarCarta.started -= instance.OnJugarCarta;
            @JugarCarta.performed -= instance.OnJugarCarta;
            @JugarCarta.canceled -= instance.OnJugarCarta;
        }

        public void RemoveCallbacks(IJ1Actions instance)
        {
            if (m_Wrapper.m_J1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJ1Actions instance)
        {
            foreach (var item in m_Wrapper.m_J1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_J1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public J1Actions @J1 => new J1Actions(this);

    // J2
    private readonly InputActionMap m_J2;
    private List<IJ2Actions> m_J2ActionsCallbackInterfaces = new List<IJ2Actions>();
    private readonly InputAction m_J2_JugarCarta;
    private readonly InputAction m_J2_GuardarCarta;
    private readonly InputAction m_J2_Navigate;
    public struct J2Actions
    {
        private @ControlesJuego m_Wrapper;
        public J2Actions(@ControlesJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @JugarCarta => m_Wrapper.m_J2_JugarCarta;
        public InputAction @GuardarCarta => m_Wrapper.m_J2_GuardarCarta;
        public InputAction @Navigate => m_Wrapper.m_J2_Navigate;
        public InputActionMap Get() { return m_Wrapper.m_J2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(J2Actions set) { return set.Get(); }
        public void AddCallbacks(IJ2Actions instance)
        {
            if (instance == null || m_Wrapper.m_J2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_J2ActionsCallbackInterfaces.Add(instance);
            @JugarCarta.started += instance.OnJugarCarta;
            @JugarCarta.performed += instance.OnJugarCarta;
            @JugarCarta.canceled += instance.OnJugarCarta;
            @GuardarCarta.started += instance.OnGuardarCarta;
            @GuardarCarta.performed += instance.OnGuardarCarta;
            @GuardarCarta.canceled += instance.OnGuardarCarta;
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
        }

        private void UnregisterCallbacks(IJ2Actions instance)
        {
            @JugarCarta.started -= instance.OnJugarCarta;
            @JugarCarta.performed -= instance.OnJugarCarta;
            @JugarCarta.canceled -= instance.OnJugarCarta;
            @GuardarCarta.started -= instance.OnGuardarCarta;
            @GuardarCarta.performed -= instance.OnGuardarCarta;
            @GuardarCarta.canceled -= instance.OnGuardarCarta;
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
        }

        public void RemoveCallbacks(IJ2Actions instance)
        {
            if (m_Wrapper.m_J2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJ2Actions instance)
        {
            foreach (var item in m_Wrapper.m_J2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_J2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public J2Actions @J2 => new J2Actions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IJ1Actions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnGuardarCarta(InputAction.CallbackContext context);
        void OnJugarCarta(InputAction.CallbackContext context);
    }
    public interface IJ2Actions
    {
        void OnJugarCarta(InputAction.CallbackContext context);
        void OnGuardarCarta(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
    }
}
